name: Validation

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.yaml"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency
        run: |
          jc_url=https://github.com/kellyjonbrazil/jc/releases/download/v1.20.1/jc_1.20.1-1_amd64.deb
          wget $jc_url -nv -O jc.deb && sudo dpkg -i jc.deb
      - name: Check
        run: |
          [ ! -d entries/json ] && mkdir entries/json
          for f in entries/yaml/*.yaml; do
            echo "Checking file: $f"
            out="${f:13}"
            content=$(cat $f | jc --yaml -p | head -n -1 | tail -n +2 | sed "s/^\s\s//")
            [ ! -z "$content" ] && echo "OK" || exit 1
          done
      - name: Fail
        if: ${{ failure() }}
        run: echo "Error" ; exit 1
      - name: Pass
        if: ${{ success() }}
        run: echo "Valid"
  automerge:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if user has write access
        id: access
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Merge pull request
        if: steps.acces.outputs.has-permission
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ secrets.PAT }}
      - name: Skip merge
        if: "! steps.access.outputs.has-permission"
        run: exit 0
